### ISSUE TITLE
Make this work without flexbox

### ISSUE THREAD

**Issue by danielthepope** [danielthepope/xkcdfull#4]
As much as I love the simple implementation of flexbox CSS in the [home page](http://xkcd.danielthepope.co.uk), the primary use of this site was to be shown using an old Raspberry Pi plugged into a TV. The Pi's browser, Midori, doesn't seem to support flexbox, which is a shame. The current workaround is to point the Pi at [/imageonly](http://xkcd.danielthepope.co.uk/imageonly), which shows the image without the text.

Can we produce the same effect without flexbox? Perhaps a small amount of JavaScript in `views/index.handlebars` could do the trick? The layout should remain the same (title on top, mouseover text + link on the bottom, comic filling all remaining space).

**Comment by loaizageorge** [comment]
I would like to work on this. I cloned the repo and when i tried to start the server with npm start i get this error.
`xkcdfull/server.js:120
 let $ = cheerio.load(data);
      ^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
`
I messed around in the developer tools in the browser and was able to maintain the same appearance with the container displayed as a block rather than a flexbox. So I know it can be done I just can't start the project on my machine. Any hints on how to get around this so I can mess around with it locally?
Cheers

**Comment by danielthepope** [comment]
Thanks for offering help! My server is using Node 6.7, and this is one of my first attempts at modern Node. Try replacing any `const` and `let` with `var` and see what that does? I've seen people write `'use strict';` as the first line, but I've never done that myself.
I'm not sure what version of Node you're using, but it needs to support template strings to run properly.

**Comment by loaizageorge** [comment]
Yea I just updated mine I was on 4.6 and it did the trick. This is the first time I'm doing this open source thing so I'll see what I can do :D
